---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tech-radar
  name: tech-radar
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: tech-radar
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tech-radar
  namespace: tech-radar
spec:
  ingressClassName: nginx-public
  rules:
    - host: radar.imaginelearning.engineering
      http:
        paths:
          - backend:
              service:
                name: tech-radar
                port:
                  name: http
            pathType: ImplementationSpecific
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tech-radar
  name: tech-radar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-radar
  template:
    metadata:
      labels:
        app: tech-radar
    spec:

      containers:
        - name: tech-radar
          image: ops/tech-radar
